name: module3_task4
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  module3_task3:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task4/setup.sh
      - run: cd module3_task4 && make build
      - run: cd module3_task4 && make unit-tests
      - run: cd module3_task4 && make integration-tests
      - run: cd module3_task4 && make validate
      - run: cd module3_task4 && make package
      - run: cd module3_task4 && npm install -g markdownlint-cli && make lint
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.1')
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          body_path: module3_task4/DEPLOY.md

