name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task3/setup.sh
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - run: cd module3_task3 && make package
      - run: cd module3_task3 && npm install -g markdownlint-cli && make lint
